# Generated by Django 4.0.5 on 2022-06-17 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='categories',
            new_name='category',
        ),
    ]
