# Generated by Django 4.0.5 on 2022-06-19 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0002_rename_categories_movie_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='category',
            new_name='categories',
        ),
    ]
